// Fotos da aba "Momentos": comissão técnica (professores) e momentos do
// campeonato. Curadoria manual — pra adicionar/trocar uma foto, é só subir
// o arquivo no bucket "fotos" do Supabase (pasta "momentos/") e colocar a
// URL pública aqui.
var MOMENTOS_BASE = "https://uggdjpzryotxiogysymi.supabase.co/storage/v1/object/public/fotos/momentos";

var MOMENTOS = {
  profs: [
    { url: MOMENTOS_BASE + "/profs-1.jpg", alt: "Professor orientando um jogador durante o jogo" },
    { url: MOMENTOS_BASE + "/profs-2.jpg", alt: "Árbitro do campeonato em campo" },
    { url: MOMENTOS_BASE + "/profs-3.jpg", alt: "Professor conferindo o horário à beira do campo" },
    { url: MOMENTOS_BASE + "/profs-4.jpg", alt: "Professor amparando um jogador" }
  ],
  campeonato: [
    { url: MOMENTOS_BASE + "/campeonato-1.jpg", alt: "Lance de um jogo do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-1.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-2.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-3.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-4.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-5.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-6.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-7.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-8.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-9.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-10.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-11.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-12.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-13.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-14.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-15.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-16.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-17.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-18.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-19.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-20.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-21.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-22.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-23.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-24.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-25.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-26.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-27.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-28.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-29.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-30.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-31.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-32.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-33.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-34.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-35.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-36.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-37.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-38.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-39.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-40.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-41.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-42.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-43.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-44.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-45.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-46.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-47.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-48.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-49.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-50.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-51.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-52.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-53.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-54.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-55.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-56.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-57.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-58.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-59.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-60.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-61.jpg", alt: "Momento do campeonato" },
    { url: MOMENTOS_BASE + "/ednilson-62.jpg", alt: "Momento do campeonato" }
  ]
};
